### ISSUE TITLE
Are you sure it works?

### ISSUE THREAD

**Issue by randombyte-developer** [BacoNetworks-Public-Projects/Ascii-Emotes#1]
https://github.com/BacoNetworks-Public-Projects/Shrug-plugin/blob/sponge/src/main/java/hdr/commands/ShrugCMD.java#L17 seems like it only sends the shrug to the player, not in the actual chat.

**Comment by HDR** [comment]
Yep, it sends it to everyone :)

**Comment by HDR** [comment]
Seems like it works one one server but not on another, currently investigating.

**Comment by HDR** [comment]
Changed it to simulateChat, it should now work as intended.
