### ISSUE TITLE
Does not respect Chat Formating

### ISSUE THREAD

**Issue by KyleFreedomSeeds** [BacoNetworks-Public-Projects/Ascii-Emotes#2]
When using any of the commands, All current chat formatting goes out the window. See below.
https://gyazo.com/9f30b849e9e13a51794b417e67818c04

**Comment by KyleFreedomSeeds** [comment]
Is this really on sponges end? We have a custom plugin that replaces chat messages like :) and <3 with their respective unicode emojis. Works like a dream. Just wondering if there is a fix :D

**Comment by HDR** [comment]
The sponge tag is because i maintain two versions, one for bukkit and one for sponge :P

**Comment by KyleFreedomSeeds** [comment]
Ohh got ya haha. my bad

**Comment by HDR** [comment]
if possible could you send me an example of your custom plugin so i can check what it does differently?

**Comment by KyleFreedomSeeds** [comment]
This is something that isnt command based. It checks chat for predefined values and replaces them with another. :) automatically gets replaced with ☺for example. Let me grab it for ya https://hastebin.com/inelezavec.swift The dev of this source code analyzed your code and it looks like the reason it doesn't respect chat formatting is that it is simulating chat rather than being an actual chat message.

**Comment by HDR** [comment]
i see, i'll look into this issue if i have some time later this week.

Edit:
I will need to use the Nucleus api to fix this, this might take me a while because the documentation is very lacking.
